POST http://localhost:3001/admin/register
Content-Type: application/json

{
  "admin_name": "nischal",
  "admin_email": "nischal@gmail.com",
  "admin_password": "password"
}

###

POST http://localhost:3001/admin/login
Content-Type: application/json

{
  "admin_email": "admin1@gmail.com",
  "admin_password": "password"
}

###

GET http://localhost:3001/admin/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIwMTI4NDczLCJleHAiOjE2MjAyMTQ4NzN9.osBqZGIdDDnBrOtQiPqXrjAb1qfSaE52Og3rY71-yuo

###

POST http://localhost:3001/auth/token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE5Nzg3MjkxLCJleHAiOjE2MjAzOTIwOTF9.9a_lwX-8CgMQI4EVXG96mYChDr_qao1NUjV2_RiNHGU"
}

###

POST http://localhost:3001/admin/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIwMTEyOTM0LCJleHAiOjE2MjAxOTkzMzR9.ScqOh90Wsvqghg7aYmClyY0A6FiThTP7E2yZmCuXZo4

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIwMTEyOTM0LCJleHAiOjE2MjA3MTc3MzR9.-8zO1dpfbTdfL9Bg_ptA8BFNOX_vY_RecnS0-YHTk-w",
}

###

POST http://localhost:3001/branch/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIwMTI4NDczLCJleHAiOjE2MjAyMTQ4NzN9.osBqZGIdDDnBrOtQiPqXrjAb1qfSaE52Og3rY71-yuo

{
  "branch_username": "isengard",
  "branch_password": "password"
}

###

GET http://localhost:3001/customer/get_branch_info
  ?customer_username=nischal
  &pin_code=700013