export const GET_ALL_BRANCHES = "GET_ALL_BRANCHES";
export const ERROR_OCCURRED = "ERROR_OCCURRED";
export const GET_BRANCH_INFO = "GET_BRANCH_INFO";
export const SAVE_ALERTS_IN_STORE = "SAVE_ALERTS_IN_STORE";
export const GET_REALTIME_ALERT = "GET_REALTIME_ALERT";
export const SAVE_ADMIN = "SAVE_ADMIN";
export const SAVE_CUSTOMER = "SAVE_CUSTOMER";
